/**
 * Curated Lucide icon set for resume header logos.
 *
 * We deliberately avoid shipping the full 3000+ icon library to the
 * search UI — only a hand-picked subset relevant to personal branding
 * (professions, industries, interests). Each entry carries lightweight
 * search keywords so typing "code" finds "CodeXml", "Laptop", "Terminal",
 * etc.
 */

import type { LucideIcon } from "lucide-react";
import {
  Anchor,
  Atom,
  Award,
  Backpack,
  Baby,
  BadgeCheck,
  Bike,
  Binary,
  BookOpen,
  Bot,
  Box,
  Brain,
  Briefcase,
  Brush,
  Building2,
  Camera,
  Car,
  ChefHat,
  CircleDashed,
  CircleDot,
  Cloud,
  Code,
  CodeXml,
  Coffee,
  Compass,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Diamond,
  Dna,
  Dumbbell,
  Earth,
  Feather,
  FileText,
  Film,
  FlaskConical,
  Flame,
  Flower2,
  Gamepad2,
  Gauge,
  Gem,
  GitBranch,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Handshake,
  Headphones,
  Heart,
  Hexagon,
  Home,
  Infinity as InfinityIcon,
  Key,
  Landmark,
  Laptop,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  Magnet,
  MapPin,
  Megaphone,
  Microscope,
  Monitor,
  Moon,
  Mountain,
  Music,
  Network,
  Newspaper,
  Package,
  Palette,
  Palmtree,
  PenTool,
  PersonStanding,
  Pill,
  Plane,
  Puzzle,
  Pyramid,
  Radio,
  Rocket,
  Satellite,
  Scale,
  School,
  Scissors,
  Server,
  Shield,
  Ship,
  ShoppingBag,
  Sigma,
  Smile,
  Sparkles,
  Sprout,
  Square,
  Star,
  Stethoscope,
  Sun,
  Target,
  Terminal,
  TreePine,
  TrendingUp,
  Trophy,
  Umbrella,
  University,
  User,
  UserCircle2,
  Users,
  Wand2,
  Watch,
  Waves,
  Wrench,
  Zap,
} from "lucide-react";

export interface LogoIconEntry {
  name: string;
  Icon: LucideIcon;
  keywords: string;
}

export const LOGO_ICONS: LogoIconEntry[] = [
  { name: "User", Icon: User, keywords: "person profile avatar" },
  { name: "UserCircle", Icon: UserCircle2, keywords: "person profile avatar circle" },
  { name: "Users", Icon: Users, keywords: "team people group" },
  { name: "Briefcase", Icon: Briefcase, keywords: "work job business career" },
  { name: "Building", Icon: Building2, keywords: "office company corporate" },
  { name: "Landmark", Icon: Landmark, keywords: "finance government legal" },
  { name: "BadgeCheck", Icon: BadgeCheck, keywords: "verified certified expert" },
  { name: "Award", Icon: Award, keywords: "achievement prize certificate" },
  { name: "Trophy", Icon: Trophy, keywords: "winner achievement award" },
  { name: "Crown", Icon: Crown, keywords: "leader executive premium" },
  { name: "Star", Icon: Star, keywords: "favorite excellent rating" },
  { name: "Sparkles", Icon: Sparkles, keywords: "magic creative shine" },
  { name: "Rocket", Icon: Rocket, keywords: "launch startup growth" },
  { name: "Target", Icon: Target, keywords: "goal focus aim precision" },
  { name: "TrendingUp", Icon: TrendingUp, keywords: "growth sales marketing" },
  { name: "Gauge", Icon: Gauge, keywords: "performance speed metric" },
  { name: "Zap", Icon: Zap, keywords: "power energy fast electric" },
  { name: "Flame", Icon: Flame, keywords: "fire hot trending" },
  { name: "Lightbulb", Icon: Lightbulb, keywords: "idea innovation creative" },
  { name: "Brain", Icon: Brain, keywords: "intelligence ai thinking" },
  { name: "Atom", Icon: Atom, keywords: "science physics research" },
  { name: "FlaskConical", Icon: FlaskConical, keywords: "science chemistry lab" },
  { name: "Microscope", Icon: Microscope, keywords: "science research biology" },
  { name: "Dna", Icon: Dna, keywords: "biology genetics science" },
  { name: "Stethoscope", Icon: Stethoscope, keywords: "doctor medical health" },
  { name: "Pill", Icon: Pill, keywords: "medicine pharma health" },
  { name: "Code", Icon: Code, keywords: "programming developer engineer" },
  { name: "CodeXml", Icon: CodeXml, keywords: "programming developer web html" },
  { name: "Terminal", Icon: Terminal, keywords: "command console developer" },
  { name: "Binary", Icon: Binary, keywords: "code developer binary" },
  { name: "Cpu", Icon: Cpu, keywords: "chip hardware computer" },
  { name: "Server", Icon: Server, keywords: "backend infrastructure cloud" },
  { name: "Database", Icon: Database, keywords: "data storage backend" },
  { name: "Cloud", Icon: Cloud, keywords: "cloud infrastructure aws azure" },
  { name: "Network", Icon: Network, keywords: "networking graph nodes" },
  { name: "GitBranch", Icon: GitBranch, keywords: "git version source control" },
  { name: "Laptop", Icon: Laptop, keywords: "computer developer remote" },
  { name: "Monitor", Icon: Monitor, keywords: "display computer screen" },
  { name: "Bot", Icon: Bot, keywords: "ai robot automation" },
  { name: "Wand2", Icon: Wand2, keywords: "magic creative automation" },
  { name: "Palette", Icon: Palette, keywords: "design art creative color" },
  { name: "PenTool", Icon: PenTool, keywords: "design writer creative" },
  { name: "Brush", Icon: Brush, keywords: "art design painter" },
  { name: "Feather", Icon: Feather, keywords: "writer author light" },
  { name: "FileText", Icon: FileText, keywords: "document writer content" },
  { name: "BookOpen", Icon: BookOpen, keywords: "book reader educator" },
  { name: "Library", Icon: Library, keywords: "books research library" },
  { name: "GraduationCap", Icon: GraduationCap, keywords: "education student academic" },
  { name: "University", Icon: University, keywords: "education academic college" },
  { name: "School", Icon: School, keywords: "education teacher" },
  { name: "Camera", Icon: Camera, keywords: "photography photographer" },
  { name: "Film", Icon: Film, keywords: "video cinema producer" },
  { name: "Music", Icon: Music, keywords: "musician audio" },
  { name: "Guitar", Icon: Guitar, keywords: "musician instrument" },
  { name: "Headphones", Icon: Headphones, keywords: "audio producer podcast" },
  { name: "Radio", Icon: Radio, keywords: "broadcast podcast audio" },
  { name: "Megaphone", Icon: Megaphone, keywords: "marketing announce" },
  { name: "Newspaper", Icon: Newspaper, keywords: "journalist news writer" },
  { name: "Scissors", Icon: Scissors, keywords: "editor stylist cut" },
  { name: "ChefHat", Icon: ChefHat, keywords: "chef cook culinary" },
  { name: "Coffee", Icon: Coffee, keywords: "coffee cafe barista" },
  { name: "Hammer", Icon: Hammer, keywords: "build maker construction" },
  { name: "Wrench", Icon: Wrench, keywords: "repair engineer mechanic" },
  { name: "Plane", Icon: Plane, keywords: "travel pilot aviation" },
  { name: "Ship", Icon: Ship, keywords: "shipping maritime travel" },
  { name: "Anchor", Icon: Anchor, keywords: "maritime stable foundation" },
  { name: "Car", Icon: Car, keywords: "automotive vehicle driver" },
  { name: "Bike", Icon: Bike, keywords: "cyclist biking fitness" },
  { name: "Dumbbell", Icon: Dumbbell, keywords: "fitness trainer gym" },
  { name: "PersonStanding", Icon: PersonStanding, keywords: "athlete sports" },
  { name: "Heart", Icon: Heart, keywords: "love care health" },
  { name: "Smile", Icon: Smile, keywords: "happy positive support" },
  { name: "Handshake", Icon: Handshake, keywords: "partnership deal sales" },
  { name: "Shield", Icon: Shield, keywords: "security protect safe" },
  { name: "Key", Icon: Key, keywords: "security access unlock" },
  { name: "CreditCard", Icon: CreditCard, keywords: "finance payment banking" },
  { name: "Scale", Icon: Scale, keywords: "legal balance justice" },
  { name: "Globe", Icon: Globe, keywords: "world international global" },
  { name: "Earth", Icon: Earth, keywords: "world planet environment" },
  { name: "MapPin", Icon: MapPin, keywords: "location travel" },
  { name: "Compass", Icon: Compass, keywords: "navigate explorer direction" },
  { name: "Mountain", Icon: Mountain, keywords: "adventure climb nature" },
  { name: "TreePine", Icon: TreePine, keywords: "nature outdoor environment" },
  { name: "Leaf", Icon: Leaf, keywords: "nature eco green" },
  { name: "Sprout", Icon: Sprout, keywords: "grow start eco" },
  { name: "Flower2", Icon: Flower2, keywords: "nature flower decorate" },
  { name: "Palmtree", Icon: Palmtree, keywords: "travel tropical vacation" },
  { name: "Waves", Icon: Waves, keywords: "ocean beach surf" },
  { name: "Sun", Icon: Sun, keywords: "sunny bright day" },
  { name: "Moon", Icon: Moon, keywords: "night calm dark" },
  { name: "Satellite", Icon: Satellite, keywords: "space telecom broadcast" },
  { name: "Pyramid", Icon: Pyramid, keywords: "geometry architecture" },
  { name: "Diamond", Icon: Diamond, keywords: "premium gem quality" },
  { name: "Gem", Icon: Gem, keywords: "premium jewelry value" },
  { name: "Hexagon", Icon: Hexagon, keywords: "shape geometry" },
  { name: "Square", Icon: Square, keywords: "shape simple" },
  { name: "CircleDot", Icon: CircleDot, keywords: "focus target simple" },
  { name: "CircleDashed", Icon: CircleDashed, keywords: "loop cycle process" },
  { name: "Infinity", Icon: InfinityIcon, keywords: "endless forever cycle" },
  { name: "Layers", Icon: Layers, keywords: "stack design architecture" },
  { name: "Box", Icon: Box, keywords: "package product" },
  { name: "Package", Icon: Package, keywords: "shipping product logistics" },
  { name: "Puzzle", Icon: Puzzle, keywords: "problem solver integration" },
  { name: "Magnet", Icon: Magnet, keywords: "attract magnetic sales" },
  { name: "Sigma", Icon: Sigma, keywords: "math sum analytics" },
  { name: "Backpack", Icon: Backpack, keywords: "student travel" },
  { name: "Watch", Icon: Watch, keywords: "time schedule" },
  { name: "Umbrella", Icon: Umbrella, keywords: "insurance protect weather" },
  { name: "ShoppingBag", Icon: ShoppingBag, keywords: "retail commerce shop" },
  { name: "Home", Icon: Home, keywords: "house real estate" },
  { name: "Gamepad", Icon: Gamepad2, keywords: "gaming esports designer" },
  { name: "Baby", Icon: Baby, keywords: "childcare parent" },
];

export function searchLogoIcons(query: string): LogoIconEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return LOGO_ICONS;
  return LOGO_ICONS.filter((e) => e.name.toLowerCase().includes(q) || e.keywords.includes(q));
}

export function findLogoIcon(name: string | undefined): LogoIconEntry | undefined {
  if (!name) return undefined;
  return LOGO_ICONS.find((e) => e.name === name);
}
